version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/ospo-book" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "devcontainers" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
